// All 80 labels the vision model (coco-ssd) recognises. Round riddle answers must
// match one of these verbatim, or the camera check can never pass.
export const COCO_CLASSES = [
  'person',
  'bicycle',
  'car',
  'motorcycle',
  'airplane',
  'bus',
  'train',
  'truck',
  'boat',
  'traffic light',
  'fire hydrant',
  'stop sign',
  'parking meter',
  'bench',
  'bird',
  'cat',
  'dog',
  'horse',
  'sheep',
  'cow',
  'elephant',
  'bear',
  'zebra',
  'giraffe',
  'backpack',
  'umbrella',
  'handbag',
  'tie',
  'suitcase',
  'frisbee',
  'skis',
  'snowboard',
  'sports ball',
  'kite',
  'baseball bat',
  'baseball glove',
  'skateboard',
  'surfboard',
  'tennis racket',
  'bottle',
  'wine glass',
  'cup',
  'fork',
  'knife',
  'spoon',
  'bowl',
  'banana',
  'apple',
  'sandwich',
  'orange',
  'broccoli',
  'carrot',
  'hot dog',
  'pizza',
  'donut',
  'cake',
  'chair',
  'couch',
  'potted plant',
  'bed',
  'dining table',
  'toilet',
  'tv',
  'laptop',
  'mouse',
  'remote',
  'keyboard',
  'cell phone',
  'microwave',
  'oven',
  'toaster',
  'sink',
  'refrigerator',
  'book',
  'clock',
  'vase',
  'scissors',
  'teddy bear',
  'hair drier',
  'toothbrush',
];

export const THEMES = ['classroom', 'home'];

// Per-theme subsets of COCO_CLASSES. A round riddle's `answer` is enum-constrained
// to whichever pool the game's theme selects — swapping this pool is what a theme
// actually changes, not just riddle wording.
export const THEME_OBJECT_POOLS = {
  // Realistic for a live classroom game — excludes home-only and outdoor/exotic items.
  classroom: [
    'person',
    'backpack',
    'handbag',
    'umbrella',
    'bottle',
    'cup',
    'banana',
    'apple',
    'sandwich',
    'orange',
    'chair',
    'dining table',
    'potted plant',
    'tv',
    'laptop',
    'mouse',
    'remote',
    'keyboard',
    'cell phone',
    'book',
    'clock',
    'scissors',
  ],
  // Everything in classroom (mostly still true at home) plus kitchen/living-room/
  // bedroom items a player could find while playing at home.
  home: [
    'person',
    'backpack',
    'umbrella',
    'handbag',
    'cat',
    'dog',
    'bottle',
    'wine glass',
    'cup',
    'fork',
    'knife',
    'spoon',
    'bowl',
    'banana',
    'apple',
    'sandwich',
    'orange',
    'chair',
    'couch',
    'potted plant',
    'bed',
    'dining table',
    'tv',
    'laptop',
    'mouse',
    'remote',
    'keyboard',
    'cell phone',
    'microwave',
    'oven',
    'toaster',
    'sink',
    'refrigerator',
    'book',
    'clock',
    'vase',
    'scissors',
    'teddy bear',
    'hair drier',
    'toothbrush',
  ],
};
