// Full label set used by @tensorflow-models/coco-ssd (COCO 2017, 80 classes).
// This is the exact vocabulary the server's object-detection model can recognise —
// any AI-generated round riddle's `answer` MUST be one of these strings verbatim,
// or the camera step in MobileRiddlePage can never register a match.
export const COCO_CLASSES = [
  'person',
  'bicycle',
  'car',
  'motorcycle',
  'airplane',
  'bus',
  'train',
  'truck',
  'boat',
  'traffic light',
  'fire hydrant',
  'stop sign',
  'parking meter',
  'bench',
  'bird',
  'cat',
  'dog',
  'horse',
  'sheep',
  'cow',
  'elephant',
  'bear',
  'zebra',
  'giraffe',
  'backpack',
  'umbrella',
  'handbag',
  'tie',
  'suitcase',
  'frisbee',
  'skis',
  'snowboard',
  'sports ball',
  'kite',
  'baseball bat',
  'baseball glove',
  'skateboard',
  'surfboard',
  'tennis racket',
  'bottle',
  'wine glass',
  'cup',
  'fork',
  'knife',
  'spoon',
  'bowl',
  'banana',
  'apple',
  'sandwich',
  'orange',
  'broccoli',
  'carrot',
  'hot dog',
  'pizza',
  'donut',
  'cake',
  'chair',
  'couch',
  'potted plant',
  'bed',
  'dining table',
  'toilet',
  'tv',
  'laptop',
  'mouse',
  'remote',
  'keyboard',
  'cell phone',
  'microwave',
  'oven',
  'toaster',
  'sink',
  'refrigerator',
  'book',
  'clock',
  'vase',
  'scissors',
  'teddy bear',
  'hair drier',
  'toothbrush',
];

// Curated subset of COCO_CLASSES: objects a player could realistically find and
// photograph in a home/office setting. Excludes large, outdoor, or exotic classes
// (e.g. "elephant", "airplane", "traffic light") that make for an unplayable riddle.
// This is the enum we constrain Gemini's round-riddle `answer` field to.
export const ROUND_RIDDLE_CLASSES = [
  'person',
  'backpack',
  'umbrella',
  'handbag',
  'tie',
  'suitcase',
  'bottle',
  'wine glass',
  'cup',
  'fork',
  'knife',
  'spoon',
  'bowl',
  'banana',
  'apple',
  'sandwich',
  'orange',
  'chair',
  'couch',
  'potted plant',
  'bed',
  'dining table',
  'tv',
  'laptop',
  'mouse',
  'remote',
  'keyboard',
  'cell phone',
  'microwave',
  'oven',
  'toaster',
  'sink',
  'refrigerator',
  'book',
  'clock',
  'vase',
  'scissors',
  'teddy bear',
  'hair drier',
  'toothbrush',
  'cat',
  'dog',
  'bicycle',
  'sports ball',
  'frisbee',
  'skateboard',
];
