// Sprint 3: replace with AI-generated riddles
export const RIDDLE_BANK = [
  { text: 'I have four legs but cannot walk. What am I?', answer: 'table' },
  { text: 'I have hands but cannot clap. What am I?', answer: 'clock' },
  { text: 'I have a face but no eyes, nose, or mouth. What am I?', answer: 'clock' },
  { text: 'I have keys but no locks. What am I?', answer: 'keyboard' },
  { text: 'I have a spine but no bones. What am I?', answer: 'book' },
  { text: 'I have a screen but no eyes. What am I?', answer: 'phone' },
  { text: 'I have legs but cannot run. What am I?', answer: 'chair' },
  { text: 'I have arms but cannot hug. What am I?', answer: 'chair' },
  { text: 'I have a mouth but cannot speak. What am I?', answer: 'bottle' },
  { text: 'I have teeth but cannot bite. What am I?', answer: 'comb' },
  { text: 'I have a lid but am not a pot. What am I?', answer: 'bin' },
  { text: 'I have a neck but no head. What am I?', answer: 'bottle' },
  { text: 'I run but have no legs. What am I?', answer: 'tap' },
  { text: 'I have a tongue but cannot taste. What am I?', answer: 'shoe' },
  { text: 'I have an eye but cannot see. What am I?', answer: 'needle' },
  { text: 'I have a tail but am not an animal. What am I?', answer: 'kite' },
  { text: 'I have a crown but am not a king. What am I?', answer: 'tooth' },
  { text: 'I have bars but am not a cage. What am I?', answer: 'phone' },
];
